//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.BillingBodies = new HashSet<BillingBody>();
            this.DataEntries = new HashSet<DataEntry>();
        }
    
        public int Act_code { get; set; }
        public string Act_code_old { get; set; }
        public string Act_description { get; set; }
        public int Aty_code { get; set; }
        public Nullable<decimal> Act_price { get; set; }
        public Nullable<int> Act_operatorUser { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<BillingBody> BillingBodies { get; set; }
        public virtual ICollection<DataEntry> DataEntries { get; set; }
    }
}
