//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        public ActivityType()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int Aty_code { get; set; }
        public string Aty_code_old { get; set; }
        public string Aty_description { get; set; }
        public string Aty_price { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
    }
}
