//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attorney
    {
        public Attorney()
        {
            this.CaseInformationSheetBodyAtts = new HashSet<CaseInformationSheetBodyAtt>();
        }
    
        public int Att_code { get; set; }
        public string Att_code_old { get; set; }
        public string Att_firstName { get; set; }
        public string Att_lastName { get; set; }
        public string Att_address { get; set; }
        public string Att_phone { get; set; }
        public string Att_fax { get; set; }
        public string Att_assistant { get; set; }
        public Nullable<int> Spe_code { get; set; }
        public bool Att_status { get; set; }
        public string Att_city { get; set; }
        public string Att_state { get; set; }
        public string Att_zipCode { get; set; }
        public string Att_zipCodeExt { get; set; }
        public Nullable<int> Att_operatorUser { get; set; }
    
        public virtual Specialty Specialty { get; set; }
        public virtual ICollection<CaseInformationSheetBodyAtt> CaseInformationSheetBodyAtts { get; set; }
    }
}
