//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingBody
    {
        public int Bib_code { get; set; }
        public string Bib_code_old { get; set; }
        public string Bib_code_ { get; set; }
        public Nullable<System.DateTime> Bib_servDate { get; set; }
        public Nullable<int> Act_code { get; set; }
        public Nullable<int> Bib_createdUser { get; set; }
        public Nullable<int> Bib_deletedUser { get; set; }
        public Nullable<System.DateTime> Bib_registerDate { get; set; }
        public Nullable<bool> Bib_deletingStatus { get; set; }
        public Nullable<int> Dae_code { get; set; }
        public Nullable<decimal> Bib_amoReim { get; set; }
        public Nullable<decimal> Bib_hourMile { get; set; }
        public Nullable<decimal> Bib_priceAct { get; set; }
        public int Bih_code { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual BillingHead BillingHead { get; set; }
        public virtual DataEntry DataEntry { get; set; }
    }
}
