//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillingHead
    {
        public BillingHead()
        {
            this.BillingBodies = new HashSet<BillingBody>();
            this.PayBodies = new HashSet<PayBody>();
        }
    
        public int Bih_code { get; set; }
        public string Bih_code_old { get; set; }
        public Nullable<int> Cis_code { get; set; }
        public Nullable<decimal> Bih_billPay { get; set; }
        public System.DateTime Bih_billDate { get; set; }
        public Nullable<decimal> Bih_billTotal { get; set; }
        public bool Bih_payStatus { get; set; }
        public int Par_code { get; set; }
        public Nullable<System.DateTime> Bih_returnDate { get; set; }
        public Nullable<System.DateTime> Bih_startWeekly { get; set; }
        public Nullable<System.DateTime> Bih_receivedDate { get; set; }
        public Nullable<System.DateTime> Bih_reimbursedDate { get; set; }
        public Nullable<int> Use_code { get; set; }
        public Nullable<bool> Bih_availability { get; set; }
        public Nullable<int> Bih_loggedUserCode { get; set; }
        public Nullable<System.DateTime> Bih_closingDate { get; set; }
        public string Bih_deleteStatus { get; set; }
        public string Bih_facNum { get; set; }
    
        public virtual ICollection<BillingBody> BillingBodies { get; set; }
        public virtual CaseInformationSheetHead CaseInformationSheetHead { get; set; }
        public virtual Parameter Parameter { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<PayBody> PayBodies { get; set; }
    }
}
