//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarioUsuarioHistorial
    {
        public int Cuh_codigo { get; set; }
        public int Cau_codigo { get; set; }
        public string Cau_tipo { get; set; }
        public System.DateTime Cau_fecha { get; set; }
        public string Use_code_old { get; set; }
        public System.DateTime Cuh_inicio { get; set; }
        public System.DateTime Cuh_fin { get; set; }
        public string Cuh_descripcion { get; set; }
        public Nullable<int> Eve_codigo { get; set; }
        public Nullable<int> Tie_codigo { get; set; }
        public Nullable<int> Use_code { get; set; }
    
        public virtual CalendarioUsuario CalendarioUsuario { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual User User { get; set; }
    }
}
