//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarioUsuario
    {
        public CalendarioUsuario()
        {
            this.CalendarioAgendas = new HashSet<CalendarioAgenda>();
            this.CalendarioUsuarioExchanges = new HashSet<CalendarioUsuarioExchange>();
            this.CalendarioUsuarioHistorials = new HashSet<CalendarioUsuarioHistorial>();
        }
    
        public int Cau_codigo { get; set; }
        public string Use_code_old { get; set; }
        public System.DateTime Cau_inicio { get; set; }
        public System.DateTime Cau_fin { get; set; }
        public string Cau_descripcion { get; set; }
        public bool Cau_vigencia { get; set; }
        public Nullable<bool> Cau_mostrarMV { get; set; }
        public Nullable<int> Eve_codigo { get; set; }
        public Nullable<int> Tie_codigo { get; set; }
        public string Cau_registeredUser_old { get; set; }
        public Nullable<bool> Cau_allday { get; set; }
        public Nullable<int> Use_code { get; set; }
        public Nullable<int> Cau_registeredUser { get; set; }
    
        public virtual ICollection<CalendarioAgenda> CalendarioAgendas { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<CalendarioUsuarioExchange> CalendarioUsuarioExchanges { get; set; }
        public virtual ICollection<CalendarioUsuarioHistorial> CalendarioUsuarioHistorials { get; set; }
    }
}
