//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseInformationSheetBodyAtt
    {
        public int Csa_code { get; set; }
        public int Cis_code { get; set; }
        public string Cis_code_old { get; set; }
        public int Att_code { get; set; }
        public string Att_code_old { get; set; }
        public bool Csa_status { get; set; }
    
        public virtual Attorney Attorney { get; set; }
        public virtual CaseInformationSheetHead CaseInformationSheetHead { get; set; }
    }
}
