//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseInformationSheetBodyMed
    {
        public int Csm_code { get; set; }
        public int Cis_code { get; set; }
        public int Med_code { get; set; }
        public string Med_code_old { get; set; }
        public bool Csm_status { get; set; }
        public Nullable<System.DateTime> Csm_date { get; set; }
        public string Csm_provenance { get; set; }
        public Nullable<int> Use_code { get; set; }
        public string Use_code_old { get; set; }
        public string Cis_code_old { get; set; }
    
        public virtual CaseInformationSheetHead CaseInformationSheetHead { get; set; }
        public virtual Medical Medical { get; set; }
        public virtual User User { get; set; }
    }
}
