//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseInformationSheetHead
    {
        public CaseInformationSheetHead()
        {
            this.BillingHeads = new HashSet<BillingHead>();
            this.CaseInformationSheetBodyAtts = new HashSet<CaseInformationSheetBodyAtt>();
            this.CaseInformationSheetBodyMeds = new HashSet<CaseInformationSheetBodyMed>();
            this.DataEntries = new HashSet<DataEntry>();
            this.Eventoes = new HashSet<Evento>();
            this.EventoHistorials = new HashSet<EventoHistorial>();
        }
    
        public int Cis_code { get; set; }
        public string Cis_code_old { get; set; }
        public Nullable<int> Ins_code { get; set; }
        public Nullable<int> Pat_code { get; set; }
        public Nullable<int> Adj_code { get; set; }
        public Nullable<int> Pro_code { get; set; }
        public decimal Cis_price { get; set; }
        public System.DateTime Cis_accidentDate { get; set; }
        public string Cis_caseCode { get; set; }
        public System.DateTime Cis_referralDate { get; set; }
        public bool Cis_status { get; set; }
        public Nullable<bool> Cis_transportation { get; set; }
        public string Cis_comment { get; set; }
        public Nullable<int> Use_Code { get; set; }
        public string Cis_Injury { get; set; }
        public string Cis_transportationCompany { get; set; }
        public Nullable<bool> Cis_translation { get; set; }
        public string Cis_translationCompany { get; set; }
        public Nullable<bool> Cis_physicalTherapy { get; set; }
        public string Cis_physicalTherapyCompany { get; set; }
        public Nullable<bool> Cis_permisionContact { get; set; }
        public string Cis_permisionContactCompany { get; set; }
        public Nullable<bool> Cis_Longshore { get; set; }
        public Nullable<bool> Cis_companyStatus { get; set; }
        public Nullable<bool> Cis_other { get; set; }
        public string Cis_otherText { get; set; }
        public Nullable<System.DateTime> Cis_registerDate { get; set; }
        public string Cis_contact1 { get; set; }
        public string Cis_contact2 { get; set; }
        public Nullable<int> Cis_caseSupervisor { get; set; }
        public Nullable<bool> Cis_presumption { get; set; }
        public Nullable<byte> Cis_acuity { get; set; }
        public Nullable<System.DateTime> Cis_closedDate { get; set; }
        public Nullable<bool> Cis_actual { get; set; }
        public Nullable<int> Cis_loggedUserCode { get; set; }
        public Nullable<bool> Cis_availability { get; set; }
        public string Ins_code_old { get; set; }
        public string Pat_code_old { get; set; }
        public string Adj_code_old { get; set; }
        public string Pro_code_old { get; set; }
        public string Use_Code_old { get; set; }
        public Nullable<System.DateTime> Cis_loggedUserDate { get; set; }
    
        public virtual Adjuster Adjuster { get; set; }
        public virtual ICollection<BillingHead> BillingHeads { get; set; }
        public virtual ICollection<CaseInformationSheetBodyAtt> CaseInformationSheetBodyAtts { get; set; }
        public virtual ICollection<CaseInformationSheetBodyMed> CaseInformationSheetBodyMeds { get; set; }
        public virtual Insurer Insurer { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<DataEntry> DataEntries { get; set; }
        public virtual ICollection<Evento> Eventoes { get; set; }
        public virtual ICollection<EventoHistorial> EventoHistorials { get; set; }
    }
}
