//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Confirmacion
    {
        public Confirmacion()
        {
            this.Eventoes = new HashSet<Evento>();
            this.EventoHistorials = new HashSet<EventoHistorial>();
        }
    
        public int Con_codigo { get; set; }
        public string Pro_code_old { get; set; }
        public string Med_code_old { get; set; }
        public System.DateTime Con_fecha { get; set; }
        public bool Con_vigencia { get; set; }
        public string Use_code_old { get; set; }
        public Nullable<bool> Con_confirmMed { get; set; }
        public Nullable<bool> Con_confirmProv { get; set; }
        public string Con_descripcion { get; set; }
        public Nullable<int> Mot_codigoMed { get; set; }
        public Nullable<int> Mot_codigoProv { get; set; }
        public Nullable<int> Pro_code { get; set; }
        public Nullable<int> Med_code { get; set; }
        public int Use_code { get; set; }
    
        public virtual Medical Medical { get; set; }
        public virtual MotivoCambioEstado MotivoCambioEstado { get; set; }
        public virtual MotivoCambioEstado MotivoCambioEstado1 { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Evento> Eventoes { get; set; }
        public virtual ICollection<EventoHistorial> EventoHistorials { get; set; }
    }
}
