//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int Cof_codigo { get; set; }
        public string Cof_descripcion { get; set; }
        public string Cof_valor { get; set; }
        public bool Cof_vigencia { get; set; }
        public string Cof_identificador { get; set; }
        public string Cof_nombre { get; set; }
        public string Cof_tipodato { get; set; }
        public string Cof_proceso { get; set; }
    }
}
