//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoEvento
    {
        public EstadoEvento()
        {
            this.Eventoes = new HashSet<Evento>();
            this.EventoHistorials = new HashSet<EventoHistorial>();
        }
    
        public byte Ese_codigo { get; set; }
        public string Ese_nombre { get; set; }
        public string Ese_descripcion { get; set; }
        public string Ese_color { get; set; }
        public string Ese_abreviatura { get; set; }
        public bool Ese_vigencia { get; set; }
        public Nullable<bool> Ese_mostrarDetailView { get; set; }
    
        public virtual ICollection<Evento> Eventoes { get; set; }
        public virtual ICollection<EventoHistorial> EventoHistorials { get; set; }
    }
}
