//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.CalendarioUsuarios = new HashSet<CalendarioUsuario>();
            this.CalendarioUsuarioHistorials = new HashSet<CalendarioUsuarioHistorial>();
            this.DataEntries = new HashSet<DataEntry>();
            this.Evento1 = new HashSet<Evento>();
            this.EventoBloqueos = new HashSet<EventoBloqueo>();
            this.EventoFiles = new HashSet<EventoFile>();
            this.EventoHistorials = new HashSet<EventoHistorial>();
            this.EventoHistorials1 = new HashSet<EventoHistorial>();
            this.EventoNextOffices = new HashSet<EventoNextOffice>();
            this.EventoNurseOverrides = new HashSet<EventoNurseOverride>();
            this.EventoTipoArchivoes = new HashSet<EventoTipoArchivo>();
            this.RecordatorioTriggers = new HashSet<RecordatorioTrigger>();
        }
    
        public int Eve_codigo { get; set; }
        public Nullable<System.DateTime> Eve_inicio { get; set; }
        public Nullable<System.DateTime> Eve_fin { get; set; }
        public Nullable<System.DateTime> Eve_fecha { get; set; }
        public string Eve_descripcion { get; set; }
        public string Pro_code_old { get; set; }
        public string Med_code_old { get; set; }
        public string Cis_code_old { get; set; }
        public int Tie_codigo { get; set; }
        public byte Ese_codigo { get; set; }
        public Nullable<int> Eve_codigoNext { get; set; }
        public string Use_code_old { get; set; }
        public string Eve_codExchange { get; set; }
        public bool Eve_descartar { get; set; }
        public Nullable<int> Con_codigo { get; set; }
        public Nullable<bool> Eve_done { get; set; }
        public Nullable<bool> Eve_override { get; set; }
        public bool Eve_allDay { get; set; }
        public Nullable<int> Mot_codigo { get; set; }
        public Nullable<int> Cat_codigo { get; set; }
        public string Eve_undoChangeUser_old { get; set; }
        public Nullable<int> Eve_codigoNov { get; set; }
        public Nullable<bool> Eve_bloqueo { get; set; }
        public Nullable<bool> Eve_nov { get; set; }
        public Nullable<bool> Eve_vigencia { get; set; }
        public string Eve_codExchangeSec { get; set; }
        public Nullable<int> Eve_statusUpdateExc { get; set; }
        public Nullable<int> Pro_code { get; set; }
        public int Med_code { get; set; }
        public int Cis_code { get; set; }
        public int Use_code { get; set; }
        public Nullable<int> Evh_undoChangeUser { get; set; }
        public Nullable<int> Eve_operatorUser { get; set; }
    
        public virtual ICollection<CalendarioUsuario> CalendarioUsuarios { get; set; }
        public virtual ICollection<CalendarioUsuarioHistorial> CalendarioUsuarioHistorials { get; set; }
        public virtual CaseInformationSheetHead CaseInformationSheetHead { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Confirmacion Confirmacion { get; set; }
        public virtual ICollection<DataEntry> DataEntries { get; set; }
        public virtual EstadoEvento EstadoEvento { get; set; }
        public virtual ICollection<Evento> Evento1 { get; set; }
        public virtual Evento Evento2 { get; set; }
        public virtual Medical Medical { get; set; }
        public virtual MotivoCambioEstado MotivoCambioEstado { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<EventoBloqueo> EventoBloqueos { get; set; }
        public virtual EventoDelete EventoDelete { get; set; }
        public virtual ICollection<EventoFile> EventoFiles { get; set; }
        public virtual ICollection<EventoHistorial> EventoHistorials { get; set; }
        public virtual ICollection<EventoHistorial> EventoHistorials1 { get; set; }
        public virtual ICollection<EventoNextOffice> EventoNextOffices { get; set; }
        public virtual ICollection<EventoNurseOverride> EventoNurseOverrides { get; set; }
        public virtual ICollection<EventoTipoArchivo> EventoTipoArchivoes { get; set; }
        public virtual ICollection<RecordatorioTrigger> RecordatorioTriggers { get; set; }
    }
}
