//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento_Audit
    {
        public Nullable<int> Eve_codigo { get; set; }
        public Nullable<System.DateTime> Eve_inicio { get; set; }
        public Nullable<System.DateTime> Eve_fin { get; set; }
        public Nullable<System.DateTime> Eve_fecha { get; set; }
        public string Eve_descripcion { get; set; }
        public string Pro_code_old { get; set; }
        public string Med_code_old { get; set; }
        public string Cis_code_old { get; set; }
        public int Tie_codigo { get; set; }
        public byte Ese_codigo { get; set; }
        public Nullable<int> Eve_codigoNext { get; set; }
        public string Use_code_old { get; set; }
        public string Eve_codExchange { get; set; }
        public bool Eve_descartar { get; set; }
        public Nullable<int> Con_codigo { get; set; }
        public Nullable<bool> Eve_done { get; set; }
        public Nullable<bool> Eve_override { get; set; }
        public bool Eve_allDay { get; set; }
        public Nullable<int> Mot_codigo { get; set; }
        public Nullable<int> Cat_codigo { get; set; }
        public string Eve_undoChangeUser_old { get; set; }
        public Nullable<int> Eve_codigoNov { get; set; }
        public Nullable<bool> Eve_bloqueo { get; set; }
        public Nullable<bool> Eve_nov { get; set; }
        public Nullable<bool> Eve_vigencia { get; set; }
        public string Eve_codExchangeSec { get; set; }
        public Nullable<int> Eve_statusUpdateExc { get; set; }
        public Nullable<int> Pro_code { get; set; }
        public int Med_code { get; set; }
        public int Cis_code { get; set; }
        public int Use_code { get; set; }
        public Nullable<int> Evh_undoChangeUser { get; set; }
        public Nullable<int> Eve_operatorUser { get; set; }
        public string AuditDataState { get; set; }
        public string AuditDMLAction { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public string UpdateColumns { get; set; }
    }
}
