//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoDelete
    {
        public int Eve_codigo { get; set; }
        public System.DateTime Evd_fecha { get; set; }
        public string Use_code_old { get; set; }
        public Nullable<int> Use_code { get; set; }
        public string Evd_motivo { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual User User { get; set; }
    }
}
