//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventoTipoArchivo
    {
        public int Tia_codigo { get; set; }
        public int Eve_codigo { get; set; }
        public byte Eta_numArchivos { get; set; }
        public bool Eta_vigencia { get; set; }
        public Nullable<byte> Eta_archivosSubidos { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual TipoArchivo TipoArchivo { get; set; }
    }
}
