//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurer
    {
        public Insurer()
        {
            this.CaseInformationSheetHeads = new HashSet<CaseInformationSheetHead>();
        }
    
        public int Ins_code { get; set; }
        public string Ins_code_old { get; set; }
        public string Ins_name { get; set; }
        public string Ins_address { get; set; }
        public string Ins_phone { get; set; }
        public string Ins_fax { get; set; }
        public string Ins_zipCode { get; set; }
        public string Ins_scTpaCode { get; set; }
        public string Ins_feinSc { get; set; }
        public string Ins_carrierCode { get; set; }
        public string Ins_feinCc { get; set; }
        public bool Ins_status { get; set; }
        public string Ins_city { get; set; }
        public string Ins_state { get; set; }
        public string Ins_zipExt { get; set; }
        public string Ins_phoneExt { get; set; }
        public Nullable<bool> Ins_availability { get; set; }
        public Nullable<int> Ins_operatorUser { get; set; }
    
        public virtual ICollection<CaseInformationSheetHead> CaseInformationSheetHeads { get; set; }
        public virtual User User { get; set; }
    }
}
