//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical
    {
        public Medical()
        {
            this.CaseInformationSheetBodyMeds = new HashSet<CaseInformationSheetBodyMed>();
            this.Confirmacions = new HashSet<Confirmacion>();
            this.Eventoes = new HashSet<Evento>();
            this.EventoHistorials = new HashSet<EventoHistorial>();
        }
    
        public int Med_code { get; set; }
        public string Med_code_old { get; set; }
        public string Med_firstName { get; set; }
        public string Med_lastName { get; set; }
        public string Med_address { get; set; }
        public string Med_phone { get; set; }
        public string Med_fax { get; set; }
        public string Med_zipCode { get; set; }
        public string Med_city { get; set; }
        public string Med_state { get; set; }
        public string Med_zipCodeExt { get; set; }
        public string Med_phoneExt { get; set; }
        public Nullable<bool> Med_status { get; set; }
        public Nullable<int> Spe_code { get; set; }
        public string Med_alternatePhone { get; set; }
        public string Med_office { get; set; }
        public Nullable<int> Med_operatorUser { get; set; }
    
        public virtual ICollection<CaseInformationSheetBodyMed> CaseInformationSheetBodyMeds { get; set; }
        public virtual ICollection<Confirmacion> Confirmacions { get; set; }
        public virtual ICollection<Evento> Eventoes { get; set; }
        public virtual ICollection<EventoHistorial> EventoHistorials { get; set; }
        public virtual Specialty Specialty { get; set; }
        public virtual User User { get; set; }
    }
}
