//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotivoCambioEstado
    {
        public MotivoCambioEstado()
        {
            this.Confirmacions = new HashSet<Confirmacion>();
            this.Confirmacions1 = new HashSet<Confirmacion>();
            this.Eventoes = new HashSet<Evento>();
            this.EventoHistorials = new HashSet<EventoHistorial>();
        }
    
        public int Mot_codigo { get; set; }
        public string Mot_descripcion { get; set; }
        public bool Mot_vigencia { get; set; }
        public System.DateTime Mot_fechaSistema { get; set; }
        public string Use_code_old { get; set; }
        public int Use_code { get; set; }
    
        public virtual ICollection<Confirmacion> Confirmacions { get; set; }
        public virtual ICollection<Confirmacion> Confirmacions1 { get; set; }
        public virtual ICollection<Evento> Eventoes { get; set; }
        public virtual ICollection<EventoHistorial> EventoHistorials { get; set; }
        public virtual User User { get; set; }
    }
}
