//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public Parameter()
        {
            this.BillingHeads = new HashSet<BillingHead>();
        }
    
        public int Par_code { get; set; }
        public System.DateTime Par_date { get; set; }
        public string Par_name { get; set; }
        public string Par_address { get; set; }
        public string Par_number { get; set; }
        public string Par_city { get; set; }
        public string Par_state { get; set; }
        public string Par_zipCode { get; set; }
        public string Par_phone { get; set; }
    
        public virtual ICollection<BillingHead> BillingHeads { get; set; }
    }
}
