//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayType
    {
        public PayType()
        {
            this.PayHeads = new HashSet<PayHead>();
        }
    
        public int Pty_code { get; set; }
        public string Pty_code_old { get; set; }
        public string Pty_description { get; set; }
        public bool Pty_Status { get; set; }
    
        public virtual ICollection<PayHead> PayHeads { get; set; }
    }
}
