//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;

    public partial class Pcase
    {
        public int CaseCode { get; set; }
        public Nullable<int> PatientCode { get; set; }
        public Nullable<int> AdjusterCode { get; set; }
        public Nullable<int> InsurerCode { get; set; }
        public Nullable<int> ProviderCode { get; set; }
        public decimal CasePrice { get; set; }
        public String CaseAccidentDate { get; set; }
        public string CaseCaseCode { get; set; }
        public String CaseReferralDate { get; set; }
        public Nullable<bool> CaseTransportation { get; set; }
        public string CaseComment { get; set; }
        public string CaseInjury { get; set; }
        public bool CaseStatus { get; set; }
        public string Patient { get; set; }
        public String Birthday { get; set; }
        public string Provider { get; set; }
        public string Adjuster { get; set; }
        public string AdjusterPhone { get; set; }
        public string AdjusterPhoneExt { get; set; }
        public string Insurer { get; set; }
        public string InsurerAddress { get; set; }
        public string InsurerCity { get; set; }
        public string InsurerState { get; set; }
        public string InsurerZipCode { get; set; }
        public string InsurerZipCodeExt { get; set; }
        public string InsurerPhone { get; set; }
        public string InsurerPhoneExt { get; set; }
        public string InsurerFax { get; set; }
        public string CaseTransportationCompany { get; set; }
        public Nullable<bool> CaseTranslation { get; set; }
        public string CaseTranslationCompany { get; set; }
        public Nullable<bool> CasePhysicalTherapy { get; set; }
        public string CasePhysicalTherapyCompany { get; set; }
        public Nullable<bool> CasePermisionContact { get; set; }
        public string CasePermisionContactCompany { get; set; }
        public Nullable<bool> CaseLongshore { get; set; }
        public Nullable<bool> CaseCompanyStatus { get; set; }
        public Nullable<bool> CaseOther { get; set; }
        public string CaseOtherText { get; set; }
        public string CaseContact1 { get; set; }
        public string CaseContact2 { get; set; }
        public Nullable<int> CaseSupervisorCode { get; set; }
        public Nullable<bool> CasePresumption { get; set; }
        public byte CaseAcuity { get; set; }
        public string CaseSupervisor { get; set; }
        public Nullable<int> cantidadTotalDeEntradas { get; set; }
    }
}
