//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.CaseInformationSheetHeads = new HashSet<CaseInformationSheetHead>();
            this.Confirmacions = new HashSet<Confirmacion>();
            this.Eventoes = new HashSet<Evento>();
            this.EventoHistorials = new HashSet<EventoHistorial>();
            this.EventoNurseOverrides = new HashSet<EventoNurseOverride>();
        }
    
        public int Pro_code { get; set; }
        public string Pro_code_old { get; set; }
        public string Pro_firstName { get; set; }
        public string Pro_lastName { get; set; }
        public string Pro_address { get; set; }
        public string Pro_phone { get; set; }
        public string Pro_fax { get; set; }
        public bool Pro_status { get; set; }
        public string Pro_number { get; set; }
        public string Pro_fein { get; set; }
        public string Pro_city { get; set; }
        public string Pro_state { get; set; }
        public string Pro_zipCode { get; set; }
        public Nullable<int> Use_code { get; set; }
        public Nullable<int> Pro_operatorUser { get; set; }
    
        public virtual ICollection<CaseInformationSheetHead> CaseInformationSheetHeads { get; set; }
        public virtual ICollection<Confirmacion> Confirmacions { get; set; }
        public virtual ICollection<Evento> Eventoes { get; set; }
        public virtual ICollection<EventoHistorial> EventoHistorials { get; set; }
        public virtual ICollection<EventoNurseOverride> EventoNurseOverrides { get; set; }
        public virtual User User { get; set; }
    }
}
