//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordatorioLog
    {
        public int Rel_codigo { get; set; }
        public int Rec_codigo { get; set; }
        public string Rec_descripcion { get; set; }
        public bool Rec_tipo { get; set; }
        public System.DateTime Rec_fechaInicio { get; set; }
        public Nullable<bool> Rec_every { get; set; }
        public Nullable<short> Rec_everydays { get; set; }
        public Nullable<bool> Rec_repetir { get; set; }
        public Nullable<byte> Rec_repetirCada { get; set; }
        public Nullable<byte> Rec_repetirDuracion { get; set; }
        public Nullable<bool> Rec_expira { get; set; }
        public Nullable<System.DateTime> Rec_fechaExpiracion { get; set; }
        public bool Rec_vigencia { get; set; }
        public Nullable<System.DateTime> Rel_fecha { get; set; }
        public string Use_code_old { get; set; }
        public Nullable<int> Use_code { get; set; }
    
        public virtual Recordatorio Recordatorio { get; set; }
        public virtual User User { get; set; }
    }
}
