//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordatorioUsuarioLog
    {
        public int Rul_codigo { get; set; }
        public int Ret_codigo { get; set; }
        public string Use_code_old { get; set; }
        public System.DateTime Rul_fecha { get; set; }
        public string Rul_accion { get; set; }
        public string Usu_codigoReg { get; set; }
        public int Use_code { get; set; }
        public Nullable<int> Rul_registeredUser { get; set; }
    
        public virtual RecordatorioTrigger RecordatorioTrigger { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
