//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordatorioTrigger
    {
        public RecordatorioTrigger()
        {
            this.Recordatorios = new HashSet<Recordatorio>();
            this.RecordatorioUsuarios = new HashSet<RecordatorioUsuario>();
            this.RecordatorioUsuarioLogs = new HashSet<RecordatorioUsuarioLog>();
        }
    
        public int Ret_codigo { get; set; }
        public int Eve_codigo { get; set; }
        public System.DateTime Ret_fecha { get; set; }
        public string Use_code_old { get; set; }
        public bool Ret_vigencia { get; set; }
        public Nullable<bool> Ret_descartar { get; set; }
        public Nullable<int> Use_code { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual ICollection<Recordatorio> Recordatorios { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<RecordatorioUsuario> RecordatorioUsuarios { get; set; }
        public virtual ICollection<RecordatorioUsuarioLog> RecordatorioUsuarioLogs { get; set; }
    }
}
