//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordatorio
    {
        public Recordatorio()
        {
            this.RecordatorioLogs = new HashSet<RecordatorioLog>();
        }
    
        public int Rec_codigo { get; set; }
        public int Ret_codigo { get; set; }
        public string Rec_descripcion { get; set; }
        public bool Rec_tipo { get; set; }
        public System.DateTime Rec_fechaInicio { get; set; }
        public Nullable<bool> Rec_every { get; set; }
        public Nullable<short> Rec_everydays { get; set; }
        public Nullable<bool> Rec_repetir { get; set; }
        public Nullable<byte> Rec_repetirCada { get; set; }
        public Nullable<byte> Rec_repetirDuracion { get; set; }
        public Nullable<bool> Rec_expira { get; set; }
        public Nullable<System.DateTime> Rec_fechaExpiracion { get; set; }
        public bool Rec_vigencia { get; set; }
        public Nullable<System.DateTime> Rec_ultimaAparicion { get; set; }
        public Nullable<System.DateTime> Rec_nextAparicion { get; set; }
    
        public virtual RecordatorioTrigger RecordatorioTrigger { get; set; }
        public virtual ICollection<RecordatorioLog> RecordatorioLogs { get; set; }
    }
}
