//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialty
    {
        public Specialty()
        {
            this.Attorneys = new HashSet<Attorney>();
            this.Medicals = new HashSet<Medical>();
        }
    
        public int Spe_code { get; set; }
        public string Spe_code_old { get; set; }
        public string Spe_name { get; set; }
        public string Spe_type { get; set; }
        public string Spe_description { get; set; }
        public Nullable<int> Spe_operatorUser { get; set; }
    
        public virtual ICollection<Attorney> Attorneys { get; set; }
        public virtual ICollection<Medical> Medicals { get; set; }
        public virtual User User { get; set; }
    }
}
