//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoEvento
    {
        public TipoEvento()
        {
            this.CalendarioUsuarios = new HashSet<CalendarioUsuario>();
            this.CalendarioUsuarioHistorials = new HashSet<CalendarioUsuarioHistorial>();
            this.Eventoes = new HashSet<Evento>();
            this.EventoHistorials = new HashSet<EventoHistorial>();
            this.TipoArchivoes = new HashSet<TipoArchivo>();
        }
    
        public int Tie_codigo { get; set; }
        public string Tie_nombre { get; set; }
        public string Tie_descripcion { get; set; }
        public bool Tie_vigencia { get; set; }
        public System.DateTime Tie_fecha { get; set; }
        public string Use_code_old { get; set; }
        public bool Tie_programable { get; set; }
        public Nullable<bool> Tie_nov { get; set; }
        public Nullable<bool> Tie_needNurse { get; set; }
        public Nullable<bool> Tie_showOnExchange { get; set; }
        public Nullable<int> Use_code { get; set; }
    
        public virtual ICollection<CalendarioUsuario> CalendarioUsuarios { get; set; }
        public virtual ICollection<CalendarioUsuarioHistorial> CalendarioUsuarioHistorials { get; set; }
        public virtual ICollection<Evento> Eventoes { get; set; }
        public virtual ICollection<EventoHistorial> EventoHistorials { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TipoArchivo> TipoArchivoes { get; set; }
    }
}
