//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Billing.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Activities = new HashSet<Activity>();
            this.Adjusters = new HashSet<Adjuster>();
            this.BillingHeads = new HashSet<BillingHead>();
            this.BillingHeads1 = new HashSet<BillingHead>();
            this.CalendarioAgendas = new HashSet<CalendarioAgenda>();
            this.CalendarioUsuarios = new HashSet<CalendarioUsuario>();
            this.CalendarioUsuarios1 = new HashSet<CalendarioUsuario>();
            this.CalendarioUsuarioExchanges = new HashSet<CalendarioUsuarioExchange>();
            this.CalendarioUsuarioHistorials = new HashSet<CalendarioUsuarioHistorial>();
            this.CaseInformationSheetBodyMeds = new HashSet<CaseInformationSheetBodyMed>();
            this.CaseInformationSheetHeads = new HashSet<CaseInformationSheetHead>();
            this.CaseInformationSheetHeads1 = new HashSet<CaseInformationSheetHead>();
            this.CaseInformationSheetHeads2 = new HashSet<CaseInformationSheetHead>();
            this.Confirmacions = new HashSet<Confirmacion>();
            this.DataEntries = new HashSet<DataEntry>();
            this.DataEntries1 = new HashSet<DataEntry>();
            this.Eventoes = new HashSet<Evento>();
            this.EventoBloqueos = new HashSet<EventoBloqueo>();
            this.EventoDeletes = new HashSet<EventoDelete>();
            this.EventoFiles = new HashSet<EventoFile>();
            this.EventoFiles1 = new HashSet<EventoFile>();
            this.EventoHistorials = new HashSet<EventoHistorial>();
            this.EventoNextOffices = new HashSet<EventoNextOffice>();
            this.EventoNurseOverrides = new HashSet<EventoNurseOverride>();
            this.Exchanges = new HashSet<Exchange>();
            this.Insurers = new HashSet<Insurer>();
            this.Medicals = new HashSet<Medical>();
            this.MotivoCambioEstadoes = new HashSet<MotivoCambioEstado>();
            this.Patients = new HashSet<Patient>();
            this.PayHeads = new HashSet<PayHead>();
            this.Providers = new HashSet<Provider>();
            this.RecordatorioLogs = new HashSet<RecordatorioLog>();
            this.RecordatorioTriggers = new HashSet<RecordatorioTrigger>();
            this.RecordatorioUsuarios = new HashSet<RecordatorioUsuario>();
            this.RecordatorioUsuarioLogs = new HashSet<RecordatorioUsuarioLog>();
            this.RecordatorioUsuarioLogs1 = new HashSet<RecordatorioUsuarioLog>();
            this.Specialties = new HashSet<Specialty>();
            this.TipoArchivoes = new HashSet<TipoArchivo>();
            this.TipoEventoes = new HashSet<TipoEvento>();
        }
    
        public int Use_code { get; set; }
        public string Use_code_old { get; set; }
        public string Use_firstName { get; set; }
        public string Use_lastName { get; set; }
        public string Use_userName { get; set; }
        public string Use_password { get; set; }
        public string Use_email { get; set; }
        public string Use_phone { get; set; }
        public string Use_address { get; set; }
        public string Use_fax { get; set; }
        public string Use_zipCode { get; set; }
        public string Use_city { get; set; }
        public string Use_state { get; set; }
        public string Use_zipCodeExt { get; set; }
        public string Use_phoneExt { get; set; }
        public bool Use_status { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Use_cellPhone { get; set; }
        public string Use_color { get; set; }
        public string Use_tipo { get; set; }
        public string Use_number { get; set; }
        public Nullable<bool> Use_inoffice { get; set; }
        public Nullable<bool> ShowonAgenda { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Adjuster> Adjusters { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<BillingHead> BillingHeads { get; set; }
        public virtual ICollection<BillingHead> BillingHeads1 { get; set; }
        public virtual ICollection<CalendarioAgenda> CalendarioAgendas { get; set; }
        public virtual ICollection<CalendarioUsuario> CalendarioUsuarios { get; set; }
        public virtual ICollection<CalendarioUsuario> CalendarioUsuarios1 { get; set; }
        public virtual ICollection<CalendarioUsuarioExchange> CalendarioUsuarioExchanges { get; set; }
        public virtual ICollection<CalendarioUsuarioHistorial> CalendarioUsuarioHistorials { get; set; }
        public virtual ICollection<CaseInformationSheetBodyMed> CaseInformationSheetBodyMeds { get; set; }
        public virtual ICollection<CaseInformationSheetHead> CaseInformationSheetHeads { get; set; }
        public virtual ICollection<CaseInformationSheetHead> CaseInformationSheetHeads1 { get; set; }
        public virtual ICollection<CaseInformationSheetHead> CaseInformationSheetHeads2 { get; set; }
        public virtual ICollection<Confirmacion> Confirmacions { get; set; }
        public virtual ICollection<DataEntry> DataEntries { get; set; }
        public virtual ICollection<DataEntry> DataEntries1 { get; set; }
        public virtual ICollection<Evento> Eventoes { get; set; }
        public virtual ICollection<EventoBloqueo> EventoBloqueos { get; set; }
        public virtual ICollection<EventoDelete> EventoDeletes { get; set; }
        public virtual ICollection<EventoFile> EventoFiles { get; set; }
        public virtual ICollection<EventoFile> EventoFiles1 { get; set; }
        public virtual ICollection<EventoHistorial> EventoHistorials { get; set; }
        public virtual ICollection<EventoNextOffice> EventoNextOffices { get; set; }
        public virtual ICollection<EventoNurseOverride> EventoNurseOverrides { get; set; }
        public virtual ICollection<Exchange> Exchanges { get; set; }
        public virtual ICollection<Insurer> Insurers { get; set; }
        public virtual ICollection<Medical> Medicals { get; set; }
        public virtual ICollection<MotivoCambioEstado> MotivoCambioEstadoes { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
        public virtual ICollection<PayHead> PayHeads { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
        public virtual ICollection<RecordatorioLog> RecordatorioLogs { get; set; }
        public virtual ICollection<RecordatorioTrigger> RecordatorioTriggers { get; set; }
        public virtual ICollection<RecordatorioUsuario> RecordatorioUsuarios { get; set; }
        public virtual ICollection<RecordatorioUsuarioLog> RecordatorioUsuarioLogs { get; set; }
        public virtual ICollection<RecordatorioUsuarioLog> RecordatorioUsuarioLogs1 { get; set; }
        public virtual ICollection<Specialty> Specialties { get; set; }
        public virtual ICollection<TipoArchivo> TipoArchivoes { get; set; }
        public virtual ICollection<TipoEvento> TipoEventoes { get; set; }
    }
}
